var PROJECTS = 
[
    {
        img:"p1.png",
        title:"project1",
        description:"asdfafasdfasd"
    },
    {
        img:"p2.jpg",
        title:"project2",
        description:"asfafgasfasfafasfaf"
    },
    {
        img:"p3.png",
        title:"project3",
        description:"asfaffasfsagafa"
    },
    {
        img:"p4.png",
        title:"project4",
        description:"afaghsagasagafaf"
    },
    {
        img:"p5.png",
        title:"project5",
        description:"afagagagasfgsgasf"
    },
    {
        img:"p6.jpg",
        title:"project6",
        description:"sghjzghsjg'zfsdg'zdg"
    },

]